@extends('layouts.admin')
@section('title', 'Backups')
@section('content')
<div class="card" style="margin-bottom:18px"><div class="card-header"><div><h3 style="margin:0">Backup Manager</h3><div class="small muted">Total {{ \App\Domain\Analytics\AnalyticsService::humanBytes($totalSize) }} · automatic backups run daily at 02:30 (Settings → Backups)</div></div>
@can('create', \App\Models\Backup::class)<form method="post" action="{{ route('admin.backups.store') }}" style="display:flex;gap:8px;align-items:center;flex-wrap:wrap">@csrf<select name="type"><option value="full">Full (files + database)</option><option value="database">Database only</option><option value="files">Files only</option></select><label class="check small"><input type="checkbox" name="encrypt" value="1"> encrypt</label><button class="btn btn-primary">Create backup now</button></form>@endcan</div>
<div class="table-wrap"><table><thead><tr><th>Created</th><th>Type</th><th>Trigger</th><th>Size</th><th>Version</th><th>Verified</th><th>Status</th><th></th></tr></thead><tbody>
@forelse($backups as $b)<tr><td>{{ $b->created_at->format('d M Y H:i') }}<div class="small muted mono">{{ $b->id }}</div></td><td>{{ $b->type }}{{ $b->encrypted ? ' 🔒' : '' }}</td><td>{{ $b->trigger }}</td><td>{{ \App\Domain\Analytics\AnalyticsService::humanBytes($b->size_bytes) }}</td><td class="small">{{ $b->app_version }}<br><span class="muted mono">{{ substr((string) $b->git_commit, 0, 7) }}</span></td><td>{{ $b->verified ? '✅' : '—' }}</td><td>@include('components.badge', ['status' => $b->status])@if($b->error)<div class="small" style="color:#fca5a5">{{ $b->error }}</div>@endif</td>
<td style="white-space:nowrap">@if($b->status === 'completed')@can('download', $b)@if($b->location)<a class="btn btn-sm btn-outline" href="{{ route('admin.backups.download', [$b, 'files']) }}">⬇ files</a>@endif @if($b->db_location)<a class="btn btn-sm btn-outline" href="{{ route('admin.backups.download', [$b, 'database']) }}">⬇ db</a>@endif @endcan
<form method="post" action="{{ route('admin.backups.verify', $b) }}" style="display:inline">@csrf<button class="btn btn-sm btn-outline">Verify</button></form>
@can('restore', $b)@if($b->db_location)<form method="post" action="{{ route('admin.backups.restore', $b) }}" style="display:inline" data-confirm-word="RESTORE" data-confirm="This will OVERWRITE the current database. Type RESTORE to continue.">@csrf<input type="hidden" name="part" value="database"><button class="btn btn-sm btn-warning">Restore DB</button></form>@endif @if($b->location)<form method="post" action="{{ route('admin.backups.restore', $b) }}" style="display:inline" data-confirm-word="RESTORE" data-confirm="This will overwrite application files (protected paths are kept). Type RESTORE to continue.">@csrf<input type="hidden" name="part" value="files"><button class="btn btn-sm btn-warning">Restore files</button></form>@endif @endcan @endif
@can('delete', $b)<form method="post" action="{{ route('admin.backups.destroy', $b) }}" style="display:inline" data-confirm="Delete backup?">@csrf @method('DELETE')<button class="btn btn-sm btn-danger">🗑</button></form>@endcan</td></tr>
@empty<tr><td colspan="8"><div class="empty">No backups yet.</div></td></tr>@endforelse</tbody></table></div>{{ $backups->links('components.pagination') }}</div>
@endsection
