@extends('layouts.admin')
@section('title', 'Scheduled Streams')
@section('content')
<div class="card" style="margin-bottom:18px"><div class="card-header"><h3>Upcoming & live</h3>@can('create', \App\Models\ScheduledStream::class)<a class="btn btn-primary" href="{{ route('admin.schedules.create') }}">+ Schedule stream</a>@endcan</div>
<div class="table-wrap"><table><thead><tr><th>Title</th><th>When</th><th>Stream key</th><th>Destinations</th><th>Auto</th><th>Status</th><th></th></tr></thead><tbody>
@forelse($upcoming as $s)<tr><td><strong>{{ $s->title }}</strong>@if($s->recording_enabled) <span class="pill">rec</span>@endif</td><td>{{ $s->scheduled_at->timezone($s->timezone)->format('d-m-Y h:i A') }}<div class="small muted">{{ $s->timezone }}@if($s->auto_stop_at) → stop {{ $s->auto_stop_at->timezone($s->timezone)->format('h:i A') }}@endif</div></td><td>{{ $s->endpoint?->name }}</td><td>{{ $s->destinations->pluck('name')->implode(', ') ?: '—' }}</td><td class="small">Start: {{ $s->auto_start ? 'YES' : 'no' }}<br>Stop: {{ $s->auto_stop ? 'YES' : 'no' }}</td><td>@include('components.badge', ['status' => $s->status])</td><td style="white-space:nowrap">@can('update', $s)<a class="btn btn-sm btn-outline" href="{{ route('admin.schedules.edit', $s) }}">Edit</a> <form method="post" action="{{ route('admin.schedules.cancel', $s) }}" style="display:inline" data-confirm="Cancel this schedule?">@csrf<button class="btn btn-sm btn-outline">Cancel</button></form>@endcan</td></tr>
@empty<tr><td colspan="7"><div class="empty">Nothing scheduled.</div></td></tr>@endforelse</tbody></table></div></div>
<div class="card"><h3>Past</h3><div class="table-wrap"><table><thead><tr><th>Title</th><th>When</th><th>Status</th><th>Session</th><th></th></tr></thead><tbody>
@forelse($past as $s)<tr><td>{{ $s->title }}</td><td>{{ $s->scheduled_at->timezone($s->timezone)->format('d-m-Y h:i A') }}</td><td>@include('components.badge', ['status' => $s->status])</td><td>@if($s->stream_session_id)<a href="{{ route('admin.history.show', $s->stream_session_id) }}">view</a>@else—@endif</td><td>@can('delete', $s)<form method="post" action="{{ route('admin.schedules.destroy', $s) }}" data-confirm="Delete?">@csrf @method('DELETE')<button class="btn btn-sm btn-outline">🗑</button></form>@endcan</td></tr>
@empty<tr><td colspan="5"><div class="empty">No past schedules.</div></td></tr>@endforelse</tbody></table></div>{{ $past->links('components.pagination') }}</div>
@endsection
