@extends('layouts.admin')
@section('title', 'Destinations')
@section('content')
<div class="card" style="margin-bottom:18px">
  <div class="card-header"><h3>Streaming destinations</h3>@can('create', \App\Models\StreamDestination::class)<div style="display:flex;gap:8px;flex-wrap:wrap">@foreach($definitions as $def)<a class="btn btn-sm btn-outline" href="{{ route('admin.destinations.create', ['platform' => $def->name]) }}">+ {{ $def->icon }} {{ $def->label }}</a>@endforeach</div>@endcan</div>
  <div class="table-wrap"><table><thead><tr><th>Platform</th><th>Name</th><th>Account</th><th>Method</th><th>Target</th><th>Key</th><th>Status</th><th>Last test</th><th>Last success</th><th></th></tr></thead><tbody>
  @forelse($destinations as $d)
    <tr><td>{{ $definitions[$d->platform]->icon ?? '' }} {{ $definitions[$d->platform]->label ?? $d->platform }}</td><td><strong>{{ $d->name }}</strong>@if($d->endpoint)<div class="small muted">key: {{ $d->endpoint->name }}</div>@endif</td><td>{{ $d->account_name ?? '—' }}</td><td>{{ strtoupper($d->connection_method) }}</td><td class="small mono">{{ $d->rtmp_url ? parse_url($d->rtmp_url, PHP_URL_HOST) : '—' }}</td><td class="mono small">{{ $d->maskedKey() }}</td>
    <td>@include('components.badge', ['status' => $d->displayStatus()])@if($d->last_error)<div class="small" style="color:#fca5a5;max-width:220px">{{ \Illuminate\Support\Str::limit($d->last_error, 80) }}<br><span class="muted">{{ $d->last_error_at?->diffForHumans() }}</span></div>@endif</td>
    <td class="small">@if($d->last_test_result)@include('components.badge', ['status' => $d->last_test_result])<div class="muted">{{ $d->last_tested_at?->diffForHumans() }}</div>@else<span class="muted">—</span>@endif</td><td class="small muted">{{ $d->last_success_at?->diffForHumans() ?? '—' }}</td>
    <td style="white-space:nowrap">@can('test', $d)<form method="post" action="{{ route('admin.destinations.test', $d) }}" style="display:inline">@csrf<button class="btn btn-sm btn-outline">Test</button></form>@endcan @can('update', $d)<a class="btn btn-sm btn-outline" href="{{ route('admin.destinations.edit', $d) }}">Edit</a><form method="post" action="{{ route('admin.destinations.toggle', $d) }}" style="display:inline">@csrf<button class="btn btn-sm btn-outline">{{ $d->is_enabled ? 'Disable' : 'Enable' }}</button></form><form method="post" action="{{ route('admin.destinations.destroy', $d) }}" style="display:inline" data-confirm="Remove destination {{ $d->name }}?">@csrf @method('DELETE')<button class="btn btn-sm btn-danger">🗑</button></form>@endcan</td></tr>
  @empty<tr><td colspan="10"><div class="empty">No destinations yet. Add YouTube, Facebook or a custom RTMP target.</div></td></tr>@endforelse
  </tbody></table></div>
</div>
<div class="card"><div class="card-header"><h3>Connected platform accounts</h3><div>@foreach(['youtube' => '▶️ Connect YouTube', 'facebook' => '📘 Connect Facebook', 'twitch' => '🎮 Connect Twitch'] as $pl => $label)@can('create', \App\Models\StreamDestination::class)<a class="btn btn-sm btn-outline" href="{{ route('admin.platforms.connect', $pl) }}">{{ $label }}</a>@endcan @endforeach</div></div>
  @forelse($accounts as $a)<div class="dest-row"><div><div class="name">{{ $a->name }} <span class="pill">{{ $a->platform }}</span></div><div class="meta">Token {{ $a->token?->expires_at ? 'expires '.$a->token->expires_at->diffForHumans() : 'no expiry' }} · {{ count($a->meta['pages'] ?? $a->meta['channels'] ?? []) }} page(s)/channel(s)</div></div><div style="display:flex;gap:6px;align-items:center">@include('components.badge', ['status' => $a->status === 'connected' ? 'connected' : 'expired'])@can('create', \App\Models\StreamDestination::class)<form method="post" action="{{ route('admin.platforms.disconnect', $a) }}" data-confirm="Disconnect and delete tokens?">@csrf @method('DELETE')<button class="btn btn-sm btn-outline">Disconnect</button></form>@endcan</div></div>@empty<div class="empty">No OAuth accounts connected. YouTube/Facebook API credentials are configured in Settings → Platforms.</div>@endforelse
</div>
@endsection
